import { ModeToggle } from "@/components/theme/ModeToggle";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <div className="flex min-h-screen flex-col items-center justify-center py-2">
          <h1 className="text-6xl font-bold text-amber-400 dark:text-amber-50">
            Welcome to Next.js!
          </h1>
          <ModeToggle />
        </div>
      </main>
    </>
  );
}
